add lab2
saba024/Android_labs pull request #11
Opened 2021-01-10 10:06 UTC by saba024

2021-01-10 18:33 UTC, gmltA commented
Пакажыце мне тое, чаго я яшчэ не бачыў.

2021-01-10 18:37 UTC, saba024 commented
Я постараюсь. Но и в этот раз я все по видео из ютуба делал. Толко сервисы и настройки оставил

2021-01-17 08:24 UTC, saba024 commented
Переделал

2021-01-28 11:16 UTC, gmltA requested changes
І гэта бачыў ужо.

2021-01-31 19:16 UTC, saba024 commented
Переделал. Возможно конечно и эту вы уже бачыли но эту я уже честно сделал полностью сам...

2021-02-11 13:36 UTC, gmltA approved these changes

2021-02-18 09:09 UTC, merged