add lab3
saba024/Android_labs pull request #13
Opened 2021-02-15 21:30 UTC by saba024

2021-02-16 13:04 UTC, gmltA requested changes
З улікам таго, што частку коду вы ўсё роўна спёрлі, з вас яшчэ падтрымка Gravatar.

2021-02-17 12:33 UTC, gmltA requested changes
![image](https://user-images.githubusercontent.com/138737/108204950-7c724100-7135-11eb-909e-fc635a9c28bd.png)

2021-02-17 15:30 UTC, gmltA requested changes
Але ж вы не выканалі заданне!

2021-02-17 15:47 UTC, saba024 commented
Так 2 конпки же есть одна граватар использует вторая firebase. А по умолчанию если firebase

2021-02-17 15:50 UTC, gmltA commented
У вас карыстальнік павінен выбіраць, адкуль будзе цягнуцца яго аватарка **заўсёды**. У вас яна хоць дзе, акрамя профіля, выкарыстоўваецца?

2021-02-17 15:57 UTC, saba024 commented
Да . Я понял вас. я тогда при регистрации чекбох на граватар сделаю.

2021-02-17 15:58 UTC, gmltA commented
Навошта мне гэта пры рэгістрацыі? Карыстальнік павінен мець магчымасць мяняць гэта ў профіле.

2021-02-17 16:15 UTC, saba024 commented
Теперь пользователь выбирает любую фотография и потом нажимает save и эта фотка идет за ним везде

2021-02-18 16:48 UTC, saba024 commented
Извините, вы сегодня еще проверяете ?

2021-02-18 22:10 UTC, saba024 commented
1 коммит правильный, остальные залились из-за решения конфликтов. После нажатия кнопки я присваиваю переменной значение граватар или обычный аватар и сохраняю ее в базу данных где ключом является пользователь который выбирал и мой выбор сохраняется навсегда(до тех пор пока сам пользователь не поменяет в профиле). Теперь дальше я могу просто брать у нужного пользователя эту переменную и в зависимости от нее загружать нужную фотку.

2021-02-19 08:10 UTC, gmltA approved these changes

2021-02-19 09:39 UTC, merged